### ISSUE TITLE
Gmail gadget still working?

### ISSUE THREAD

**Issue by xunwangnv** [jalmeroth/gadget-things#1]
Hi,

I'm curious as if this gadget prototype is still working?

I've been trying to get contextual gadgets working for the past few days.. without success.

I tried to deploy your repository , and followed instructions.  Deployment was completed onto my domain.. however the Gadget interface just doesnt' show up..

Wondering if I'm missing anything?

Thanks!

**Comment by jalmeroth** [comment]
Hi,

yes it is still in production here. Is there anything specific that does not work for you while setting it up?

Let me know, if there is anything I can help you with.

Cheers!

**Comment by xunwangnv** [comment]
Hi,

Thanks for responding.

I can complete all the setup and deployment steps successfully.

However, when going into gmail, for my domain.  I don't see the gadget coming up.  So it seems to be not be triggering at all.

I've deployed your gadget xml here: http://snappy-bucksaw-89506.appspot.com/gadget/things.xml
Screenshot of configuration from developer console: https://drive.google.com/file/d/0Bwg1UHHbJFkpQURkUDZQSmV6VnM/view
Screenshot of google apps admin console: https://drive.google.com/file/d/0Bwg1UHHbJFkpcm51S1lvUjY2YlE/view

Do you know if there are any logs or debug information to figure out why this is not actually showing up in the gmail window?  Everything seems to be configured properly, but it just doesn't work and silently fails.

Thanks!

**Comment by jalmeroth** [comment]
What I can see from your screenshots is that you better use a secure URL (https) to your Gadget.
I will have a deeper look into it over the weekend. Maybe there some issues with the used scopes for authorization.

**Comment by xunwangnv** [comment]
Tried switching it to https, but gadget still doesn't trigger..

Are there any other settings in the google apps admin console that has to be specially set?

**Comment by jalmeroth** [comment]
Hi there,

I just replayed the whole deployment and it works for me like advertised.

Do you see the app icon in the application switcher menu? 
![screen shot 2015-03-29 at 19 49 26](https://cloud.githubusercontent.com/assets/4163868/6886862/d3ee47f6-d64c-11e4-8d6a-88162a1b926a.png)
Which browser do you use on which platform? Have you tried a different one?

Cheers,
Jan

**Comment by jalmeroth** [comment]
Oh, and I just saw in your screenshot above, that you need to select the right Scope 'Mail - **Raw** Subject Line' instead of 'Mail - Subject Line'. :)

**Comment by xunwangnv** [comment]
Awesome, it's working now!

Thanks!

**Comment by jalmeroth** [comment]
You are welcome. If there is any feature missing, please let me know. :)
